export default {
  base: '#fff',
  baseText: '#000',
  overlayTextBackground: '#1119',
  tabIconDefault: '#ccc',
  tabIconSelected: '#2f95dc',
  tabSelectedUnderline: '#A32921',
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: '#2f95dc',
  noticeText: '#fff',
};
